<!DOCTYPE html>
<html>
<head>
    <title>Monthly Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #4f46e5; color: white; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { margin-top: 30px; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ $title }}</h2>
        <p>Report for the Month of {{ $date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Title</th>
                <th>Author</th>
                <th>Status</th>
                <th>Released</th>
            </tr>
        </thead>
        <tbody>
            @foreach($researches as $res)
            <tr>
                <td>{{ $res->created_at->format('M d, Y') }}</td>
                <td>{{ $res->title }}</td>
                <td>{{ $res->author }}</td>
                <td>{{ $res->status }}</td>
                <td>{{ $res->released_date ?? 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $developer }} on {{ now()->format('M d, Y H:i A') }}</p>
    </div>
</body>
</html>